# info
https://www.guru99.com/import-module-python.html
https://realpython.com/working-with-files-in-python/
https://www.educative.io/edpresso/how-to-list-files-in-a-directory-in-python
https://www.geeksforgeeks.org/how-to-read-multiple-text-files-from-folder-in-python/
https://datatofish.com/txt-files-directory-python/

https://pyyaml.org/wiki/PyYAMLDocumentation
https://stackoverflow.com/questions/1773805/how-can-i-parse-a-yaml-file-in-python